### ISSUE TITLE
Unirest wont install

### ISSUE THREAD

**Issue by acaciabengo** [Mashape/unirest-nodejs#36]
When i run npm install unirest

npm install unirest
npm http GET https://registry.npmjs.org/unirest
npm http 304 https://registry.npmjs.org/unirest
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/request
npm ERR! Error: No compatible version found: form-data@'^0.2.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.0","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.0.8","0.0.9","0.0.10","0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.2.0"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:685:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:607:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-279.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "unirest"
npm ERR! cwd /var/www/html/smpp
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm http 304 https://registry.npmjs.org/mime
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/html/smpp/npm-debug.log
npm ERR! not ok code 0

**Comment by Nijikokun** [comment]
Try upgrading NPM and see if that solves the issue, I just attempted an
install and it works fine for me. Currently using version 2.1.8 on my side,
I see you are quite behind with version 1.2.18

**Comment by Nijikokun** [comment]
Also clear your npm cache as it appears that it's fetching the information
from cache

**Comment by acaciabengo** [comment]
Thank you @Nijikokun . Upgrade worked!

**Comment by Nijikokun** [comment]
No problem glad to be of assistance :)!
