### ISSUE TITLE
Multipart attachment issue

### ISSUE THREAD

**Issue by stavros-zavrakas** [Mashape/unirest-nodejs#37]
Hi there,
I was looking the documentation here:
http://unirest.io/nodejs.html

about the Request.attach(Object) or (name, path) section.
As I see there are three ways to attach a file (I tried the first two):
.attach({
  (1) 'file': 'dog.png', 
  (2) 'relative file': fs.createReadStream(path.join(__dirname, 'dog.png'),
  (3) 'remote file': unirest.request('http://google.com/doodle.png')
}).

I found a bug on the second way using the fs.createReadStream way. Basically I don't know if it is a bug or you would like to drop the functionality because as I see it is also not tested. Anyway I will try to explain. Using the second way I get back this error:
" Uncaught Error: ENAMETOOLONG, open '/home/svabael/projects/unirest-nodejs/tests/{"_readableState":{"highWaterMark":65536,"buffer":[],"length":0,"pipes":null,"pipesCount":0,"flowing":false,"ended":false,"endEmitted":false,"reading":false,"calledRead":false,"sync":true,"needReadable":false,"emittedReadable":false,"readableListening":false,"objectMode":false,"defaultEncoding":"utf8","ranOut":false,"awaitDrain":0,"readingMore":false,"decoder":null,"encoding":null},"readable":true,"domain":null,"_events":{},"_maxListeners":10,"path":"/home/cambridge/projects/unirest-nodejs/README.md","fd":null,"flags":"r","mode":438,"autoClose":true}' ".

As I see in the handleField function (line 625 - index.js) possibly we have to check if the value is an object because finally this is what the fs.createReadStream returns and send as parameter in the handleFieldValue the value.path. As a result we assign as the value of the field instead of a string, that is the path but the whole object.
And then in the handleFormData function (508 line - index.js) we are assigning the whole object as a parameter into the fs.createReadStream function that finally throws the error above. I don' t know if you need to drop this functionality or fix it. If you need to fix it and not to drop it just let me know and I can create a patch and test for this.

Thank you for your time!

**Comment by Nijikokun** [comment]
I think fixing it would be the best route
