### ISSUE TITLE
Memroy leak

### ISSUE THREAD

**Issue by doron2402** [Mashape/unirest-nodejs#44]
hi guys I'm using hapi and lab for testing used one of your code ex' and got an error for memory leak.
`
var unirest = require('unirest');
var url = some url goes here...
	var request = unirest.get(url);
	request.query({
		paramA: this.getMetroId({}),

	})
	.headers({ 'Accept': 'application/json' })
	.end(function (response) {
		var error = null;
		if (!response || response === ''){
			error = 'empty response';
		}

		return cb(error, response.body);
	});

`

that's the error i got when running my test
`The following leaks were detected:Unirest`

as you can see i used `unirest` all lower case after short investigation i found it in your code guys. now I switch to request.js no memory leak found.

I would love to use your node module but there are some issue.

thanks,
- Doron.

**Comment by Nijikokun** [comment]
Not a memory leak, simply a global leak. I've fixed the issue in 0.4.0.
