### ISSUE TITLE
cannot get 'http-only; secure" cookie from res.cookies

### ISSUE THREAD

**Issue by anklos** [Mashape/unirest-nodejs#50]
Hi there,

I am trying to read cookies from a `get` response using `res.cookies`. I can get most cookies as I get from browser, except the cookie marked as `http-only` and `secure`.

So my question is why the `http-only; secure` cookie can be seen in browser cookies but not in `res.cookies`? 

Thanks.

**Comment by Nijikokun** [comment]
Are you using HTTP(s) ?

**Comment by anklos** [comment]
yes

**Comment by anklos** [comment]
yes, the get request url is https.

**Comment by Nijikokun** [comment]
Can you give me example code?

**Comment by anklos** [comment]
```
 request = unirest.get "https://xxxxx"

  request.end( (res) ->
    console.log res.cookies
  )
```

**Comment by Nijikokun** [comment]
Look at the cookies header(s):

```js
res.headers['cookie']
res.headers['set-cookies']
```

**Comment by anklos** [comment]
the content in `res.headers['cookie']`, `res.headers['set-cookies']` and `res.cookies` are the same.

if there is no such limitation top off your head, it probably because the cookie in the browser was stored from previous requests.

**Comment by Nijikokun** [comment]
Yes, a session based cookie

**Comment by anklos** [comment]
very likely. thanks!

**Comment by anklos** [comment]
@Nijikokun OK find the reason. Because the request was redirected a few times. The data in `set-cookie` of the first request was not recorded in the final response `res.cookie`.

Is there a way to get the `set-cookie` in the first redirected response?

Thanks!

![image](https://cloud.githubusercontent.com/assets/530145/6777142/bab3d244-d19a-11e4-9c15-4cbc9af23316.png)

**Comment by Nijikokun** [comment]
Looking into it, might be an issue in the underlying library

**Comment by anklos** [comment]
i tested with `request`, it also not returns `set-cookie` from first redirect.

**Comment by Nijikokun** [comment]
I've opened an issue on request https://github.com/request/request/issues/1502
