### ISSUE TITLE
Custom JSON Content-Type on response avoids json parsing

### ISSUE THREAD

**Issue by nicosommi** [Mashape/unirest-nodejs#53]
Hello, I found this issue in which if you set a custom Content-Type header on the response like for example application/vnd.api+json then the response body is not parsed as JSON when checking the unirest's response, even if you use the provided type method to allow different content types.
I made a gist for this that reproduces the issue.

## Instructions for gist:
```
 git clone https://gist.github.com/8bea1437f615c0c64163.git
 cd 8bea1437f615c0c64163
 npm install
 npm test
```

Gist source on https://gist.github.com/nicosommi/8bea1437f615c0c64163

**Comment by Nijikokun** [comment]
Nice catch.

However, `.json` is for **sending** not `receiving`, Unirest checks the content type for parsing that.

I will add a check later tonight for `+json`

**Comment by dcrockwell** [comment]
@Nijikokun Could you clarify what you mean by .json being for sending and not receiving?

**Comment by Nijikokun** [comment]
`.json` is telling it what `Content-Type` header to **send** with the request for the payload / body.

Not what to use to interpret the response body as.
