### ISSUE TITLE
Header/Type not working correctly

### ISSUE THREAD

**Issue by nicosommi** [Mashape/unirest-nodejs#55]
Hello, following the README.md Create Request section I found that there is an issue setting the content-type for a post request. Tried both with type method and the header method. I made a gist for it.

## Steps to reproduce it
1) git clone https://gist.github.com/6917b308ecaf1a64fd5f.git
2) npm install
3) DEBUG=* npm test

You will see that the body parser says that the request has the content type set to "application/x-www-form-urlencoded"

**Comment by Nijikokun** [comment]
This is already reported in #53

**Comment by nicosommi** [comment]
@Nijikokun it is not. They are different issues. One refers to the header is not sent and the other that the received header is not used correctly.

**Comment by Nijikokun** [comment]
You're right, my apologies, I read this quickly, I'll run the tests specified now and see if I can debug this.

**Comment by Nijikokun** [comment]
@nicosommi can you try master and let me know if that solves your issues? There are tests but I want to confirm before releasing the version.

**Comment by nicosommi** [comment]
@Nijikokun yep both gists working

**Comment by Nijikokun** [comment]
Perfect, publishing :+1:
