### ISSUE TITLE
Unirest stuck in a loop

### ISSUE THREAD

**Issue by davidgatti** [Mashape/unirest-nodejs#70]
I have two servers on NodeJS

- one creates posts requests using Unrest (sending file)
- second accepts them using Multer (receiving file).

On the receiving server after getting many requests the server will start to log `POST / - - ms - -`. When this happens Unirest will get a undefined status. My log looks like this `Worker: 18208 - File didn't reach the server. Response: undefined`.

Instead of dropping the connection, Unirest keeps sending the request even if my code finished working. 

Unirest will stop this behavior if I kill the receiving server. 

Any idea what is happening?

**Comment by Nijikokun** [comment]
Could you create a test case for this? I could not replicate it.

**Comment by davidgatti** [comment]
@nijikokun i finally figure the issue out. It is defiantly not your fault :) In my code I wasn't sending a state response. Adding the right status after processing the request solved the problem.

```
res.status(200).end();
```

Sorry for the confusion.
