### ISSUE TITLE
Request.as.json doesn't do a thing

### ISSUE THREAD

**Issue by ncruces** [Mashape/unirest-nodejs#79]
`Request.as.json` is simply an alias for `Request.end`.

Facebook's Graph API, just to cite a popular instance, sends content-type `text/javascript` by default, which means unirest won't automatically parse the response body.

It'd be useful if instead of being an alias, `Request.as.json(cb)` was the equivalent of:
```javascript
Request.header('Accept', 'application/json').end(cb)
```

Which fixes more than a few instances of non standard content-types being used.

Would you guys fancy a pull request?

PS: Don't know what should/could be done about `Request.as.binary`?

**Comment by Nijikokun** [comment]
I'm not sure about the binary one either, perhaps octet. It is simply an alias to the Java, variant of unirest wouldn't mind a pull request at all.

It would be a breaking change however considering that it would now do something.

**Comment by ncruces** [comment]
Yes, definitely a breaking change. I wonder though, being an alias, does this get any usage?

About binary, how does unirest handle binary data? Does getting back `application/octet-stream` make a difference?
