### ISSUE TITLE
Node security project failure

### ISSUE THREAD

**Issue by bobjflong** [Mashape/unirest-nodejs#83]
Hi, we are getting `nsp` failures in [intercom-node](https://github.com/intercom/intercom-node). We are running unirest 0.4.2 which appears to be the latest. There was a change https://github.com/Mashape/unirest-nodejs/commit/dddf899ad0cfbb29aefeab8e278e618811b5e70e to bump the `request` version but did it get released? And do you think it will fix the `hawk` issue?

```
┌───────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│               │ Regular Expression Denial of Service                                                                      │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Name          │ hawk                                                                                                      │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Installed     │ 1.1.1                                                                                                     │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Vulnerable    │ < 3.1.3  || >= 4.0.0 <4.1.1                                                                               │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Patched       │ >=3.1.3 < 4.0.0 || >=4.1.1                                                                                │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Path          │ intercom-client@2.6.0 > unirest@0.4.2 > request@2.51.0 > hawk@1.1.1                                       │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ More Info     │ https://nodesecurity.io/advisories/77                                                                     │
└───────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by joeycozza** [comment]
Sure would be nice to have this update released on npm...

**Comment by bobjflong** [comment]
Our builds are still broken :disappointed: would it be possible to release the version? Or learn more about when that might happen?

**Comment by ErikBean** [comment]
@bobjflong  I bumped my unirest version to point to master: 
`"unirest": "git@github.com:Mashape/unirest-nodejs.git#master"`
And nsp is no longer complaining about request, since it's bumped to ~2.65.0 in unirest's master branch. 
So I believe this issue should be fixed in the next release. 
I also would like to have this added to npm, how can I help?
@nijikokun is there a plan for when the next release might be out?

**Comment by nijikokun** [comment]
today

**Comment by joeycozza** [comment]
hallelujah

**Comment by nijikokun** [comment]
0.5.0 has been released, beware that I have updated all module dependencies to their latest (safe) version that I can foresee. Let me know if you spot any issues.

**Comment by ErikBean** [comment]
@nijikokun I'm confused, I don't see 0.5.0 in the releases page, but I see 0.5.0 on npm. How is this working?

**Comment by nijikokun** [comment]
you dont have to push tags to github for it to show on npm

**Comment by ErikBean** [comment]
Ok, thanks 👍
