### ISSUE TITLE
Authentication with custom headers possible?

### ISSUE THREAD

**Issue by georg90** [Mashape/unirest-nodejs#87]
I have an API which requires two custom headers to authenticate:

```
username: username
signature: base64 encoded HMAC 
```

If I set these headers with `Request.headers()` I get a 401 response, since the headers need to be set before the request.

Can this be done with unirest?

**Comment by nijikokun** [comment]
```
unirest.post('http://mockbin.com/request')
.headers({'Content-Type': 'multipart/form-data'})
```
