### ISSUE TITLE
Need help on upload the assets in github using Unirest 

### ISSUE THREAD

**Issue by gopikrishnaA** [Mashape/unirest-nodejs#89]
Need help for the uploading the assets in gitHUb using unirest api. please help on this.

`curl -X POST -H 'Authorization: token <token>' -H "Content-Type:octet-stream" --data-binary @temp/file.exe "http://<upload_url>/repos/:owner/:repo/releases/:id/assets?name=file.zip"`

**Comment by nijikokun** [comment]
```
unirest.post('http://mockbin.com/request')
.headers({'Content-Type': 'multipart/form-data'})
.field('parameter', 'value') // Form field
.attach('file', '/tmp/file') // Attachment
.end(function (response) {
  console.log(response.body);
});
```

Example of how to upload a file from the readme, you can change the headers in the headers method to your required headers.
